BooksList Tab
wolox-training/sf-react-native pull request #18
Opened 2018-06-15 19:23 UTC by sfernandez11

# Summary
## Features
* Added a BooksList tab with a list of books with book picture, the title and the author
## Screenshots
### Android
![image](https://user-images.githubusercontent.com/8583214/41485799-6110533c-70b8-11e8-9d3e-a88cda33d028.png)

## Trello Card
https://trello.com/c/39D1W203/5-componentes-ii-listado-de-libros

2018-06-15 19:29 UTC, IgnacioAbadie requested changes
Just a little change

2018-06-15 19:29 UTC, IgnacioAbadie commented on src/config/api.js
> +const baseURL = ' http://192.168.122.1:3005';
should be on .env file

2018-06-15 19:29 UTC, IgnacioAbadie commented on src/config/api.js
> +    console.warn('API baseURL has not been properly initialized');
remove this if

2018-06-18 14:43 UTC, sfernandez11 commented on src/config/api.js
> +const baseURL = ' http://192.168.122.1:3005';
Done

2018-06-18 14:43 UTC, sfernandez11 commented on src/config/api.js
> +    console.warn('API baseURL has not been properly initialized');
Done

2018-06-18 14:46 UTC, IgnacioAbadie approved these changes

2018-06-18 14:46 UTC, merged